-- 코드를 입력하세요



# SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * 30 AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS A
# # ON A.CAR_TYPE = B.CAR_TYPE
# WHERE A.CAR_ID NOT IN (SELECT CAR_ID
#                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                        GROUP BY CAR_ID
#                        HAVING '2022-11-01' <= MAX(END_DATE)
#                        ORDER BY CAR_ID) AND A.CAR_TYPE IN ('세단', 'SUV')
                       

SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE((A.DAILY_FEE *((100-B.DISCOUNT_RATE) / 100)) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       GROUP BY CAR_ID
                       HAVING '2022-11-01' <= MAX(END_DATE)
                       ORDER BY CAR_ID) AND A.CAR_TYPE IN ('세단', 'SUV') AND B.DURATION_TYPE = '30일 이상'
                       AND (500000 <= (A.DAILY_FEE *((100-B.DISCOUNT_RATE) / 100)) * 30 AND (A.DAILY_FEE *((100-B.DISCOUNT_RATE) /                        100)) * 30 < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
