 -- 코드를 입력하세요
SELECT A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(B.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A
JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE YEAR(B.SALES_DATE) = 2022 AND MONTH(B.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;